// Fake product catalog for the Tossavi PS Gaming Store
window.STORE_DATA = {
  categories: [
    { id: 'controllers', name: 'Manettes', en: 'Controllers', count: 128 },
    { id: 'headsets',    name: 'Casques',  en: 'Headsets',    count: 42  },
    { id: 'stands',      name: 'Stands',   en: 'Stands',      count: 17  },
    { id: 'wheels',      name: 'Volants',  en: 'Wheels',      count: 9   },
    { id: 'merch',       name: 'Merch',    en: 'Merch',       count: 96  },
    { id: 'cards',       name: 'Cartes PSN', en: 'PSN Cards', count: 12 },
  ],

  products: [
    {
      id: 'dualsense-edge',
      name: 'DualSense Edge',
      brand: 'Sony',
      platform: 'PS5',
      category: 'controllers',
      price: 239.99,
      currency: '€',
      tag: 'NEW',
      colors: ['#0E1014', '#F5F5F2'],
      shape: 'controller',
      tone: 'dark',
      badge: 'Nouveau',
      desc: 'Manette pro sur-mesure. Sticks remplaçables, profils personnalisés, latence ultra-basse.',
      specs: [
        ['Compatibilité', 'PS5, PC'],
        ['Connectivité',  'Sans fil + USB-C'],
        ['Batterie',      '~10h'],
        ['Poids',         '325 g'],
      ],
      stock: 12,
    },
    {
      id: 'dualsense-cosmic-red',
      name: 'DualSense Cosmic Red',
      brand: 'Sony',
      platform: 'PS5',
      category: 'controllers',
      price: 74.99,
      original: 79.99,
      currency: '€',
      colors: ['#E14B4B', '#0E1014'],
      shape: 'controller',
      tone: 'red',
      desc: 'Manette officielle PS5, finition rouge cosmique.',
      specs: [],
      stock: 47,
    },
    {
      id: 'pulse-3d',
      name: 'Casque Pulse 3D Wireless',
      brand: 'Pulse',
      platform: 'PS5',
      category: 'headsets',
      price: 74.90,
      original: 99.99,
      currency: '€',
      tag: 'SALE',
      badge: '−25%',
      colors: ['#F5F5F2', '#0E1014'],
      shape: 'headset',
      tone: 'light',
      desc: 'Audio 3D Tempest, double micro avec réduction de bruit.',
      specs: [],
      stock: 3,
    },
    {
      id: 'pulse-elite',
      name: 'Pulse Elite',
      brand: 'Pulse',
      platform: 'PS5',
      category: 'headsets',
      price: 149.99,
      currency: '€',
      tag: 'NEW',
      colors: ['#0E1014'],
      shape: 'headset',
      tone: 'dark',
      desc: 'Casque sans fil haut de gamme, batterie 30h.',
      specs: [],
      stock: 22,
    },
    {
      id: 'charging-stand',
      name: 'Station de charge',
      brand: 'Sony',
      platform: 'PS5',
      category: 'stands',
      price: 29.99,
      currency: '€',
      colors: ['#F5F5F2'],
      shape: 'stand',
      tone: 'light',
      desc: 'Charge deux DualSense simultanément.',
      specs: [],
      stock: 88,
    },
    {
      id: 'gourde-tossavi',
      name: 'Gourde Tossavi · 750ml',
      brand: 'Tossavi',
      platform: 'GOODIES',
      category: 'merch',
      price: 24.90,
      currency: '€',
      tag: 'LIMITED',
      badge: 'Édition limitée',
      colors: ['#0E1014', '#C6FF3D'],
      shape: 'bottle',
      tone: 'dark',
      desc: 'Inox double paroi, isotherme 12h. Logo gravé.',
      specs: [],
      stock: 56,
    },
    {
      id: 'racing-wheel-t300',
      name: 'Volant T300 RS',
      brand: 'Thrustmaster',
      platform: 'PS5',
      category: 'wheels',
      price: 369.00,
      currency: '€',
      colors: ['#0E1014'],
      shape: 'wheel',
      tone: 'dark',
      desc: 'Volant force feedback 1080°. Compatible PS4/PS5/PC.',
      specs: [],
      stock: 7,
    },
    {
      id: 'psn-50',
      name: 'Carte PSN · 50 €',
      brand: 'Sony',
      platform: 'DIGITAL',
      category: 'cards',
      price: 50.00,
      currency: '€',
      colors: ['#0070D1'],
      shape: 'card',
      tone: 'blue',
      desc: 'Crédit PlayStation Store, livré par email.',
      specs: [],
      stock: 999,
    },
    {
      id: 'hoodie-tossavi',
      name: 'Hoodie Tossavi · Squad',
      brand: 'Tossavi',
      platform: 'GOODIES',
      category: 'merch',
      price: 69.00,
      currency: '€',
      colors: ['#0E1014', '#5A5E68'],
      shape: 'hoodie',
      tone: 'dark',
      desc: 'Coton bio 380g, broderie poitrine. Fit relax.',
      specs: [],
      stock: 31,
    },
    {
      id: 'mug-controller',
      name: 'Mug DualSense',
      brand: 'Tossavi',
      platform: 'GOODIES',
      category: 'merch',
      price: 14.90,
      currency: '€',
      colors: ['#F5F5F2'],
      shape: 'mug',
      tone: 'light',
      desc: 'Céramique 350ml, illustration des touches PS.',
      specs: [],
      stock: 124,
    },
    {
      id: 'arcade-stick',
      name: 'Stick arcade Pro',
      brand: 'HORI',
      platform: 'PS5',
      category: 'controllers',
      price: 199.00,
      currency: '€',
      tag: 'NEW',
      colors: ['#0E1014'],
      shape: 'arcade',
      tone: 'dark',
      desc: 'Stick fightstick licence officielle, boutons HORI.',
      specs: [],
      stock: 14,
    },
    {
      id: 'stand-cooling',
      name: 'Stand vertical + ventilation',
      brand: 'Tossavi',
      platform: 'PS5',
      category: 'stands',
      price: 39.90,
      currency: '€',
      colors: ['#F5F5F2', '#0E1014'],
      shape: 'stand',
      tone: 'light',
      desc: 'Refroidit ta console et range tes manettes.',
      specs: [],
      stock: 65,
    },
  ],
};
